//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ColpatriaSAI.Negocio.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(LiquidacionReglaxParticipante))]
    [KnownType(typeof(SubRegla))]
    [KnownType(typeof(DetalleLiquidacionSubRegla))]
    public partial class DetalleLiquidacionRegla: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public Nullable<int> liquidacionReglaxParticipante_id
        {
            get { return _liquidacionReglaxParticipante_id; }
            set
            {
                if (_liquidacionReglaxParticipante_id != value)
                {
                    ChangeTracker.RecordOriginalValue("liquidacionReglaxParticipante_id", _liquidacionReglaxParticipante_id);
                    if (!IsDeserializing)
                    {
                        if (LiquidacionReglaxParticipante != null && LiquidacionReglaxParticipante.id != value)
                        {
                            LiquidacionReglaxParticipante = null;
                        }
                    }
                    _liquidacionReglaxParticipante_id = value;
                    OnPropertyChanged("liquidacionReglaxParticipante_id");
                }
            }
        }
        private Nullable<int> _liquidacionReglaxParticipante_id;
    
        [DataMember]
        public Nullable<int> subregla_id
        {
            get { return _subregla_id; }
            set
            {
                if (_subregla_id != value)
                {
                    ChangeTracker.RecordOriginalValue("subregla_id", _subregla_id);
                    if (!IsDeserializing)
                    {
                        if (SubRegla != null && SubRegla.id != value)
                        {
                            SubRegla = null;
                        }
                    }
                    _subregla_id = value;
                    OnPropertyChanged("subregla_id");
                }
            }
        }
        private Nullable<int> _subregla_id;
    
        [DataMember]
        public Nullable<bool> resultado
        {
            get { return _resultado; }
            set
            {
                if (_resultado != value)
                {
                    _resultado = value;
                    OnPropertyChanged("resultado");
                }
            }
        }
        private Nullable<bool> _resultado;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public LiquidacionReglaxParticipante LiquidacionReglaxParticipante
        {
            get { return _liquidacionReglaxParticipante; }
            set
            {
                if (!ReferenceEquals(_liquidacionReglaxParticipante, value))
                {
                    var previousValue = _liquidacionReglaxParticipante;
                    _liquidacionReglaxParticipante = value;
                    FixupLiquidacionReglaxParticipante(previousValue);
                    OnNavigationPropertyChanged("LiquidacionReglaxParticipante");
                }
            }
        }
        private LiquidacionReglaxParticipante _liquidacionReglaxParticipante;
    
        [DataMember]
        public SubRegla SubRegla
        {
            get { return _subRegla; }
            set
            {
                if (!ReferenceEquals(_subRegla, value))
                {
                    var previousValue = _subRegla;
                    _subRegla = value;
                    FixupSubRegla(previousValue);
                    OnNavigationPropertyChanged("SubRegla");
                }
            }
        }
        private SubRegla _subRegla;
    
        [DataMember]
        public TrackableCollection<DetalleLiquidacionSubRegla> DetalleLiquidacionSubReglas
        {
            get
            {
                if (_detalleLiquidacionSubReglas == null)
                {
                    _detalleLiquidacionSubReglas = new TrackableCollection<DetalleLiquidacionSubRegla>();
                    _detalleLiquidacionSubReglas.CollectionChanged += FixupDetalleLiquidacionSubReglas;
                }
                return _detalleLiquidacionSubReglas;
            }
            set
            {
                if (!ReferenceEquals(_detalleLiquidacionSubReglas, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_detalleLiquidacionSubReglas != null)
                    {
                        _detalleLiquidacionSubReglas.CollectionChanged -= FixupDetalleLiquidacionSubReglas;
                    }
                    _detalleLiquidacionSubReglas = value;
                    if (_detalleLiquidacionSubReglas != null)
                    {
                        _detalleLiquidacionSubReglas.CollectionChanged += FixupDetalleLiquidacionSubReglas;
                    }
                    OnNavigationPropertyChanged("DetalleLiquidacionSubReglas");
                }
            }
        }
        private TrackableCollection<DetalleLiquidacionSubRegla> _detalleLiquidacionSubReglas;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            LiquidacionReglaxParticipante = null;
            SubRegla = null;
            DetalleLiquidacionSubReglas.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupLiquidacionReglaxParticipante(LiquidacionReglaxParticipante previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.DetalleLiquidacionReglas.Contains(this))
            {
                previousValue.DetalleLiquidacionReglas.Remove(this);
            }
    
            if (LiquidacionReglaxParticipante != null)
            {
                if (!LiquidacionReglaxParticipante.DetalleLiquidacionReglas.Contains(this))
                {
                    LiquidacionReglaxParticipante.DetalleLiquidacionReglas.Add(this);
                }
    
                liquidacionReglaxParticipante_id = LiquidacionReglaxParticipante.id;
            }
            else if (!skipKeys)
            {
                liquidacionReglaxParticipante_id = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("LiquidacionReglaxParticipante")
                    && (ChangeTracker.OriginalValues["LiquidacionReglaxParticipante"] == LiquidacionReglaxParticipante))
                {
                    ChangeTracker.OriginalValues.Remove("LiquidacionReglaxParticipante");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("LiquidacionReglaxParticipante", previousValue);
                }
                if (LiquidacionReglaxParticipante != null && !LiquidacionReglaxParticipante.ChangeTracker.ChangeTrackingEnabled)
                {
                    LiquidacionReglaxParticipante.StartTracking();
                }
            }
        }
    
        private void FixupSubRegla(SubRegla previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.DetalleLiquidacionReglas.Contains(this))
            {
                previousValue.DetalleLiquidacionReglas.Remove(this);
            }
    
            if (SubRegla != null)
            {
                if (!SubRegla.DetalleLiquidacionReglas.Contains(this))
                {
                    SubRegla.DetalleLiquidacionReglas.Add(this);
                }
    
                subregla_id = SubRegla.id;
            }
            else if (!skipKeys)
            {
                subregla_id = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("SubRegla")
                    && (ChangeTracker.OriginalValues["SubRegla"] == SubRegla))
                {
                    ChangeTracker.OriginalValues.Remove("SubRegla");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("SubRegla", previousValue);
                }
                if (SubRegla != null && !SubRegla.ChangeTracker.ChangeTrackingEnabled)
                {
                    SubRegla.StartTracking();
                }
            }
        }
    
        private void FixupDetalleLiquidacionSubReglas(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (DetalleLiquidacionSubRegla item in e.NewItems)
                {
                    item.DetalleLiquidacionRegla = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("DetalleLiquidacionSubReglas", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (DetalleLiquidacionSubRegla item in e.OldItems)
                {
                    if (ReferenceEquals(item.DetalleLiquidacionRegla, this))
                    {
                        item.DetalleLiquidacionRegla = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("DetalleLiquidacionSubReglas", item);
                    }
                }
            }
        }

        #endregion
    }
}
