//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ColpatriaSAI.Negocio.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(FactorxNota))]
    [KnownType(typeof(Meta))]
    [KnownType(typeof(Modelo))]
    public partial class ModeloxMeta: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public Nullable<double> peso
        {
            get { return _peso; }
            set
            {
                if (_peso != value)
                {
                    _peso = value;
                    OnPropertyChanged("peso");
                }
            }
        }
        private Nullable<double> _peso;
    
        [DataMember]
        public Nullable<int> modelo_id
        {
            get { return _modelo_id; }
            set
            {
                if (_modelo_id != value)
                {
                    ChangeTracker.RecordOriginalValue("modelo_id", _modelo_id);
                    if (!IsDeserializing)
                    {
                        if (Modelo != null && Modelo.id != value)
                        {
                            Modelo = null;
                        }
                    }
                    _modelo_id = value;
                    OnPropertyChanged("modelo_id");
                }
            }
        }
        private Nullable<int> _modelo_id;
    
        [DataMember]
        public Nullable<int> meta_id
        {
            get { return _meta_id; }
            set
            {
                if (_meta_id != value)
                {
                    ChangeTracker.RecordOriginalValue("meta_id", _meta_id);
                    if (!IsDeserializing)
                    {
                        if (Meta != null && Meta.id != value)
                        {
                            Meta = null;
                        }
                    }
                    _meta_id = value;
                    OnPropertyChanged("meta_id");
                }
            }
        }
        private Nullable<int> _meta_id;
    
        [DataMember]
        public Nullable<int> factorxnota_id
        {
            get { return _factorxnota_id; }
            set
            {
                if (_factorxnota_id != value)
                {
                    ChangeTracker.RecordOriginalValue("factorxnota_id", _factorxnota_id);
                    if (!IsDeserializing)
                    {
                        if (FactorxNota != null && FactorxNota.id != value)
                        {
                            FactorxNota = null;
                        }
                    }
                    _factorxnota_id = value;
                    OnPropertyChanged("factorxnota_id");
                }
            }
        }
        private Nullable<int> _factorxnota_id;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public FactorxNota FactorxNota
        {
            get { return _factorxNota; }
            set
            {
                if (!ReferenceEquals(_factorxNota, value))
                {
                    var previousValue = _factorxNota;
                    _factorxNota = value;
                    FixupFactorxNota(previousValue);
                    OnNavigationPropertyChanged("FactorxNota");
                }
            }
        }
        private FactorxNota _factorxNota;
    
        [DataMember]
        public Meta Meta
        {
            get { return _meta; }
            set
            {
                if (!ReferenceEquals(_meta, value))
                {
                    var previousValue = _meta;
                    _meta = value;
                    FixupMeta(previousValue);
                    OnNavigationPropertyChanged("Meta");
                }
            }
        }
        private Meta _meta;
    
        [DataMember]
        public Modelo Modelo
        {
            get { return _modelo; }
            set
            {
                if (!ReferenceEquals(_modelo, value))
                {
                    var previousValue = _modelo;
                    _modelo = value;
                    FixupModelo(previousValue);
                    OnNavigationPropertyChanged("Modelo");
                }
            }
        }
        private Modelo _modelo;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            FactorxNota = null;
            Meta = null;
            Modelo = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupFactorxNota(FactorxNota previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.ModeloxMetas.Contains(this))
            {
                previousValue.ModeloxMetas.Remove(this);
            }
    
            if (FactorxNota != null)
            {
                if (!FactorxNota.ModeloxMetas.Contains(this))
                {
                    FactorxNota.ModeloxMetas.Add(this);
                }
    
                factorxnota_id = FactorxNota.id;
            }
            else if (!skipKeys)
            {
                factorxnota_id = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("FactorxNota")
                    && (ChangeTracker.OriginalValues["FactorxNota"] == FactorxNota))
                {
                    ChangeTracker.OriginalValues.Remove("FactorxNota");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("FactorxNota", previousValue);
                }
                if (FactorxNota != null && !FactorxNota.ChangeTracker.ChangeTrackingEnabled)
                {
                    FactorxNota.StartTracking();
                }
            }
        }
    
        private void FixupMeta(Meta previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.ModeloxMetas.Contains(this))
            {
                previousValue.ModeloxMetas.Remove(this);
            }
    
            if (Meta != null)
            {
                if (!Meta.ModeloxMetas.Contains(this))
                {
                    Meta.ModeloxMetas.Add(this);
                }
    
                meta_id = Meta.id;
            }
            else if (!skipKeys)
            {
                meta_id = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Meta")
                    && (ChangeTracker.OriginalValues["Meta"] == Meta))
                {
                    ChangeTracker.OriginalValues.Remove("Meta");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Meta", previousValue);
                }
                if (Meta != null && !Meta.ChangeTracker.ChangeTrackingEnabled)
                {
                    Meta.StartTracking();
                }
            }
        }
    
        private void FixupModelo(Modelo previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.ModeloxMetas.Contains(this))
            {
                previousValue.ModeloxMetas.Remove(this);
            }
    
            if (Modelo != null)
            {
                if (!Modelo.ModeloxMetas.Contains(this))
                {
                    Modelo.ModeloxMetas.Add(this);
                }
    
                modelo_id = Modelo.id;
            }
            else if (!skipKeys)
            {
                modelo_id = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Modelo")
                    && (ChangeTracker.OriginalValues["Modelo"] == Modelo))
                {
                    ChangeTracker.OriginalValues.Remove("Modelo");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Modelo", previousValue);
                }
                if (Modelo != null && !Modelo.ChangeTracker.ChangeTrackingEnabled)
                {
                    Modelo.StartTracking();
                }
            }
        }

        #endregion
    }
}
