//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ColpatriaSAI.Negocio.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Plan))]
    [KnownType(typeof(ProductoDetalle))]
    [KnownType(typeof(Negocio))]
    [KnownType(typeof(Recaudo))]
    [KnownType(typeof(PersistenciadeCAPIDetalle))]
    [KnownType(typeof(FactorComisionFija))]
    [KnownType(typeof(FactorComisionVariableNeto))]
    [KnownType(typeof(FactorComisionVariableNuevo))]
    public partial class PlanDetalle: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public string nombre
        {
            get { return _nombre; }
            set
            {
                if (_nombre != value)
                {
                    _nombre = value;
                    OnPropertyChanged("nombre");
                }
            }
        }
        private string _nombre;
    
        [DataMember]
        public Nullable<int> productoDetalle_id
        {
            get { return _productoDetalle_id; }
            set
            {
                if (_productoDetalle_id != value)
                {
                    ChangeTracker.RecordOriginalValue("productoDetalle_id", _productoDetalle_id);
                    if (!IsDeserializing)
                    {
                        if (ProductoDetalle != null && ProductoDetalle.id != value)
                        {
                            ProductoDetalle = null;
                        }
                    }
                    _productoDetalle_id = value;
                    OnPropertyChanged("productoDetalle_id");
                }
            }
        }
        private Nullable<int> _productoDetalle_id;
    
        [DataMember]
        public Nullable<int> plan_id
        {
            get { return _plan_id; }
            set
            {
                if (_plan_id != value)
                {
                    ChangeTracker.RecordOriginalValue("plan_id", _plan_id);
                    if (!IsDeserializing)
                    {
                        if (Plan != null && Plan.id != value)
                        {
                            Plan = null;
                        }
                    }
                    _plan_id = value;
                    OnPropertyChanged("plan_id");
                }
            }
        }
        private Nullable<int> _plan_id;
    
        [DataMember]
        public string codigoCore
        {
            get { return _codigoCore; }
            set
            {
                if (_codigoCore != value)
                {
                    _codigoCore = value;
                    OnPropertyChanged("codigoCore");
                }
            }
        }
        private string _codigoCore;
    
        [DataMember]
        public Nullable<bool> Activo
        {
            get { return _activo; }
            set
            {
                if (_activo != value)
                {
                    _activo = value;
                    OnPropertyChanged("Activo");
                }
            }
        }
        private Nullable<bool> _activo;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Plan Plan
        {
            get { return _plan; }
            set
            {
                if (!ReferenceEquals(_plan, value))
                {
                    var previousValue = _plan;
                    _plan = value;
                    FixupPlan(previousValue);
                    OnNavigationPropertyChanged("Plan");
                }
            }
        }
        private Plan _plan;
    
        [DataMember]
        public ProductoDetalle ProductoDetalle
        {
            get { return _productoDetalle; }
            set
            {
                if (!ReferenceEquals(_productoDetalle, value))
                {
                    var previousValue = _productoDetalle;
                    _productoDetalle = value;
                    FixupProductoDetalle(previousValue);
                    OnNavigationPropertyChanged("ProductoDetalle");
                }
            }
        }
        private ProductoDetalle _productoDetalle;
    
        [DataMember]
        public TrackableCollection<Negocio> Negocios
        {
            get
            {
                if (_negocios == null)
                {
                    _negocios = new TrackableCollection<Negocio>();
                    _negocios.CollectionChanged += FixupNegocios;
                }
                return _negocios;
            }
            set
            {
                if (!ReferenceEquals(_negocios, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_negocios != null)
                    {
                        _negocios.CollectionChanged -= FixupNegocios;
                    }
                    _negocios = value;
                    if (_negocios != null)
                    {
                        _negocios.CollectionChanged += FixupNegocios;
                    }
                    OnNavigationPropertyChanged("Negocios");
                }
            }
        }
        private TrackableCollection<Negocio> _negocios;
    
        [DataMember]
        public TrackableCollection<Recaudo> Recaudoes
        {
            get
            {
                if (_recaudoes == null)
                {
                    _recaudoes = new TrackableCollection<Recaudo>();
                    _recaudoes.CollectionChanged += FixupRecaudoes;
                }
                return _recaudoes;
            }
            set
            {
                if (!ReferenceEquals(_recaudoes, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_recaudoes != null)
                    {
                        _recaudoes.CollectionChanged -= FixupRecaudoes;
                    }
                    _recaudoes = value;
                    if (_recaudoes != null)
                    {
                        _recaudoes.CollectionChanged += FixupRecaudoes;
                    }
                    OnNavigationPropertyChanged("Recaudoes");
                }
            }
        }
        private TrackableCollection<Recaudo> _recaudoes;
    
        [DataMember]
        public TrackableCollection<PersistenciadeCAPIDetalle> PersistenciadeCAPIDetalles
        {
            get
            {
                if (_persistenciadeCAPIDetalles == null)
                {
                    _persistenciadeCAPIDetalles = new TrackableCollection<PersistenciadeCAPIDetalle>();
                    _persistenciadeCAPIDetalles.CollectionChanged += FixupPersistenciadeCAPIDetalles;
                }
                return _persistenciadeCAPIDetalles;
            }
            set
            {
                if (!ReferenceEquals(_persistenciadeCAPIDetalles, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_persistenciadeCAPIDetalles != null)
                    {
                        _persistenciadeCAPIDetalles.CollectionChanged -= FixupPersistenciadeCAPIDetalles;
                    }
                    _persistenciadeCAPIDetalles = value;
                    if (_persistenciadeCAPIDetalles != null)
                    {
                        _persistenciadeCAPIDetalles.CollectionChanged += FixupPersistenciadeCAPIDetalles;
                    }
                    OnNavigationPropertyChanged("PersistenciadeCAPIDetalles");
                }
            }
        }
        private TrackableCollection<PersistenciadeCAPIDetalle> _persistenciadeCAPIDetalles;
    
        [DataMember]
        public TrackableCollection<FactorComisionFija> FactorComisionFijas
        {
            get
            {
                if (_factorComisionFijas == null)
                {
                    _factorComisionFijas = new TrackableCollection<FactorComisionFija>();
                    _factorComisionFijas.CollectionChanged += FixupFactorComisionFijas;
                }
                return _factorComisionFijas;
            }
            set
            {
                if (!ReferenceEquals(_factorComisionFijas, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_factorComisionFijas != null)
                    {
                        _factorComisionFijas.CollectionChanged -= FixupFactorComisionFijas;
                    }
                    _factorComisionFijas = value;
                    if (_factorComisionFijas != null)
                    {
                        _factorComisionFijas.CollectionChanged += FixupFactorComisionFijas;
                    }
                    OnNavigationPropertyChanged("FactorComisionFijas");
                }
            }
        }
        private TrackableCollection<FactorComisionFija> _factorComisionFijas;
    
        [DataMember]
        public TrackableCollection<FactorComisionVariableNeto> FactorComisionVariableNetoes
        {
            get
            {
                if (_factorComisionVariableNetoes == null)
                {
                    _factorComisionVariableNetoes = new TrackableCollection<FactorComisionVariableNeto>();
                    _factorComisionVariableNetoes.CollectionChanged += FixupFactorComisionVariableNetoes;
                }
                return _factorComisionVariableNetoes;
            }
            set
            {
                if (!ReferenceEquals(_factorComisionVariableNetoes, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_factorComisionVariableNetoes != null)
                    {
                        _factorComisionVariableNetoes.CollectionChanged -= FixupFactorComisionVariableNetoes;
                    }
                    _factorComisionVariableNetoes = value;
                    if (_factorComisionVariableNetoes != null)
                    {
                        _factorComisionVariableNetoes.CollectionChanged += FixupFactorComisionVariableNetoes;
                    }
                    OnNavigationPropertyChanged("FactorComisionVariableNetoes");
                }
            }
        }
        private TrackableCollection<FactorComisionVariableNeto> _factorComisionVariableNetoes;
    
        [DataMember]
        public TrackableCollection<FactorComisionVariableNuevo> FactorComisionVariableNuevoes
        {
            get
            {
                if (_factorComisionVariableNuevoes == null)
                {
                    _factorComisionVariableNuevoes = new TrackableCollection<FactorComisionVariableNuevo>();
                    _factorComisionVariableNuevoes.CollectionChanged += FixupFactorComisionVariableNuevoes;
                }
                return _factorComisionVariableNuevoes;
            }
            set
            {
                if (!ReferenceEquals(_factorComisionVariableNuevoes, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_factorComisionVariableNuevoes != null)
                    {
                        _factorComisionVariableNuevoes.CollectionChanged -= FixupFactorComisionVariableNuevoes;
                    }
                    _factorComisionVariableNuevoes = value;
                    if (_factorComisionVariableNuevoes != null)
                    {
                        _factorComisionVariableNuevoes.CollectionChanged += FixupFactorComisionVariableNuevoes;
                    }
                    OnNavigationPropertyChanged("FactorComisionVariableNuevoes");
                }
            }
        }
        private TrackableCollection<FactorComisionVariableNuevo> _factorComisionVariableNuevoes;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Plan = null;
            ProductoDetalle = null;
            Negocios.Clear();
            Recaudoes.Clear();
            PersistenciadeCAPIDetalles.Clear();
            FactorComisionFijas.Clear();
            FactorComisionVariableNetoes.Clear();
            FactorComisionVariableNuevoes.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupPlan(Plan previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PlanDetalles.Contains(this))
            {
                previousValue.PlanDetalles.Remove(this);
            }
    
            if (Plan != null)
            {
                if (!Plan.PlanDetalles.Contains(this))
                {
                    Plan.PlanDetalles.Add(this);
                }
    
                plan_id = Plan.id;
            }
            else if (!skipKeys)
            {
                plan_id = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Plan")
                    && (ChangeTracker.OriginalValues["Plan"] == Plan))
                {
                    ChangeTracker.OriginalValues.Remove("Plan");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Plan", previousValue);
                }
                if (Plan != null && !Plan.ChangeTracker.ChangeTrackingEnabled)
                {
                    Plan.StartTracking();
                }
            }
        }
    
        private void FixupProductoDetalle(ProductoDetalle previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PlanDetalles.Contains(this))
            {
                previousValue.PlanDetalles.Remove(this);
            }
    
            if (ProductoDetalle != null)
            {
                if (!ProductoDetalle.PlanDetalles.Contains(this))
                {
                    ProductoDetalle.PlanDetalles.Add(this);
                }
    
                productoDetalle_id = ProductoDetalle.id;
            }
            else if (!skipKeys)
            {
                productoDetalle_id = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ProductoDetalle")
                    && (ChangeTracker.OriginalValues["ProductoDetalle"] == ProductoDetalle))
                {
                    ChangeTracker.OriginalValues.Remove("ProductoDetalle");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ProductoDetalle", previousValue);
                }
                if (ProductoDetalle != null && !ProductoDetalle.ChangeTracker.ChangeTrackingEnabled)
                {
                    ProductoDetalle.StartTracking();
                }
            }
        }
    
        private void FixupNegocios(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Negocio item in e.NewItems)
                {
                    item.PlanDetalle = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Negocios", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Negocio item in e.OldItems)
                {
                    if (ReferenceEquals(item.PlanDetalle, this))
                    {
                        item.PlanDetalle = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Negocios", item);
                    }
                }
            }
        }
    
        private void FixupRecaudoes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Recaudo item in e.NewItems)
                {
                    item.PlanDetalle = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Recaudoes", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Recaudo item in e.OldItems)
                {
                    if (ReferenceEquals(item.PlanDetalle, this))
                    {
                        item.PlanDetalle = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Recaudoes", item);
                    }
                }
            }
        }
    
        private void FixupPersistenciadeCAPIDetalles(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (PersistenciadeCAPIDetalle item in e.NewItems)
                {
                    item.PlanDetalle = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PersistenciadeCAPIDetalles", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PersistenciadeCAPIDetalle item in e.OldItems)
                {
                    if (ReferenceEquals(item.PlanDetalle, this))
                    {
                        item.PlanDetalle = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PersistenciadeCAPIDetalles", item);
                    }
                }
            }
        }
    
        private void FixupFactorComisionFijas(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (FactorComisionFija item in e.NewItems)
                {
                    item.PlanDetalle = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("FactorComisionFijas", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FactorComisionFija item in e.OldItems)
                {
                    if (ReferenceEquals(item.PlanDetalle, this))
                    {
                        item.PlanDetalle = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("FactorComisionFijas", item);
                    }
                }
            }
        }
    
        private void FixupFactorComisionVariableNetoes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (FactorComisionVariableNeto item in e.NewItems)
                {
                    item.PlanDetalle = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("FactorComisionVariableNetoes", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FactorComisionVariableNeto item in e.OldItems)
                {
                    if (ReferenceEquals(item.PlanDetalle, this))
                    {
                        item.PlanDetalle = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("FactorComisionVariableNetoes", item);
                    }
                }
            }
        }
    
        private void FixupFactorComisionVariableNuevoes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (FactorComisionVariableNuevo item in e.NewItems)
                {
                    item.PlanDetalle = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("FactorComisionVariableNuevoes", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FactorComisionVariableNuevo item in e.OldItems)
                {
                    if (ReferenceEquals(item.PlanDetalle, this))
                    {
                        item.PlanDetalle = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("FactorComisionVariableNuevoes", item);
                    }
                }
            }
        }

        #endregion
    }
}
