//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ColpatriaSAI.Negocio.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(EstadoProceso))]
    public partial class ProcesoLiquidacion: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public Nullable<int> tipo
        {
            get { return _tipo; }
            set
            {
                if (_tipo != value)
                {
                    _tipo = value;
                    OnPropertyChanged("tipo");
                }
            }
        }
        private Nullable<int> _tipo;
    
        [DataMember]
        public Nullable<int> liquidacion_id
        {
            get { return _liquidacion_id; }
            set
            {
                if (_liquidacion_id != value)
                {
                    _liquidacion_id = value;
                    OnPropertyChanged("liquidacion_id");
                }
            }
        }
        private Nullable<int> _liquidacion_id;
    
        [DataMember]
        public Nullable<System.DateTime> fechaInicio
        {
            get { return _fechaInicio; }
            set
            {
                if (_fechaInicio != value)
                {
                    _fechaInicio = value;
                    OnPropertyChanged("fechaInicio");
                }
            }
        }
        private Nullable<System.DateTime> _fechaInicio;
    
        [DataMember]
        public Nullable<int> estadoProceso_id
        {
            get { return _estadoProceso_id; }
            set
            {
                if (_estadoProceso_id != value)
                {
                    ChangeTracker.RecordOriginalValue("estadoProceso_id", _estadoProceso_id);
                    if (!IsDeserializing)
                    {
                        if (EstadoProceso != null && EstadoProceso.id != value)
                        {
                            EstadoProceso = null;
                        }
                    }
                    _estadoProceso_id = value;
                    OnPropertyChanged("estadoProceso_id");
                }
            }
        }
        private Nullable<int> _estadoProceso_id;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public EstadoProceso EstadoProceso
        {
            get { return _estadoProceso; }
            set
            {
                if (!ReferenceEquals(_estadoProceso, value))
                {
                    var previousValue = _estadoProceso;
                    _estadoProceso = value;
                    FixupEstadoProceso(previousValue);
                    OnNavigationPropertyChanged("EstadoProceso");
                }
            }
        }
        private EstadoProceso _estadoProceso;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            EstadoProceso = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupEstadoProceso(EstadoProceso previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.ProcesoLiquidacions.Contains(this))
            {
                previousValue.ProcesoLiquidacions.Remove(this);
            }
    
            if (EstadoProceso != null)
            {
                if (!EstadoProceso.ProcesoLiquidacions.Contains(this))
                {
                    EstadoProceso.ProcesoLiquidacions.Add(this);
                }
    
                estadoProceso_id = EstadoProceso.id;
            }
            else if (!skipKeys)
            {
                estadoProceso_id = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("EstadoProceso")
                    && (ChangeTracker.OriginalValues["EstadoProceso"] == EstadoProceso))
                {
                    ChangeTracker.OriginalValues.Remove("EstadoProceso");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("EstadoProceso", previousValue);
                }
                if (EstadoProceso != null && !EstadoProceso.ChangeTracker.ChangeTrackingEnabled)
                {
                    EstadoProceso.StartTracking();
                }
            }
        }

        #endregion
    }
}
